### ISSUE TITLE
Merge Buckets on ZbMap

### ISSUE THREAD

**Issue by Zelldon** [zeebe-io/zb-util#33]
On removing entry/block the reverse operation of split (called merge) should be executed if possible.

Follow up of #31

**Comment by Zelldon** [comment]
New merging behavior:
   
     After an entry is removed it will be tried to merge the bucket:
    
     * If the bucket is an overflow bucket it will be tried to merge it into
       the parent bucket.
     * If the bucket is an bucket with an overflow pointer it will be tried
       to merge the overflow bucket into the current bucket.
     * If the bucket is a split bucket without an overflow bucket, then
       the bucket id is calculated via the depth minus one XIR with the current
       bucket id.
     ** If the calculated id is larger, then the current id this
        means the bucket was splitted again. In this case we have to try to
        merge the child bucket with this parent.
     ** If the calculated id is smaller then the current bucket id this means the current bucket is the
     child bucket.
    
     On the merge of split buckets the depth have to be equal. If they are
     not equal this means the parent was splitted again. This have to be
     merged before!
    
     The bucket have to be removable from the bucket buffer
     array. It is removable when the bucket is the last bucket in the
     current bucket buffer. We can only remove these buckets since the
     bucket address consist of the bucket buffer id and the bucket offset.
    
     The child and parent bucket have to be mergable, which means the fill
     count of both have not be equal to the maximum fill count. Would we
     merge buckets on which the parent is filled we have to split again on
     the next add entry, which will recreate the merged bucket.
    
     Merging of split buckets relocates the blocks, removes the bucket
     updates the hash table and decrease the parent bucket depth.
    
     After the merging was successful and the bucket was removed either
     an overflow bucket or split bucket the merging method is called
     recursively until a bucket can't be merged. This means that on
     removing some entries a bunch of buckets can be freed at once.
    
     Added benchmarks for the remove from map.
    

I used some functionality from #31 to implement the merge and reverted some other.
I will close #31 please write all review hints in this issue. The commit from #31 is 
https://github.com/zeebe-io/zb-util/commit/bdc8a321785cfcd48f6088c31b98e7f9613aa8d8 .
I think it is easier if you review the commits from this issue and the `removeBucket` and `releaseBucketBuffers` method from the BucketBufferArray, these are the leftovers from #31 .

**Comment by Zelldon** [comment]
I pushed the fix for the reusing freed buckets on a branch https://github.com/zeebe-io/zb-util/commit/6dbbe7cc60b36d78549a84cddd1f4abf82f2d75c , since we are still on a release. 
Maybe you can take a look @ThorbenLindhauer 

Greets
Chris

**Comment by ThorbenLindhauer** [comment]
Review hints:

h3. Javadoc

* `ZbMap` constructor docs seem outdated
* The map has a physical layout (flat bucket buffer array) and a conceptual layout (buckets are organized in a binary tree). The physical layout is documented well. If we document conceptual layout better, it will be easier to understand the implemented concepts. This makes it easier to reason about things like split, merge and overflow
* `ZbMapBucketMergeHelper`
** The merge concept should be described from the perspective of the calling code, i.e. what is the result of reorganization when invoking this method, not so much how that result is achieved. This can be described via the map's binary-tree concept, e.g. have one before-after ascii art per merge case.
* We reuse the space for removed buckets only in rather specific circumstances (creating a new bucket always appends to the last bucket buffer, removing can happen in any bucket buffer, this results in fragmentation which is only resolved when we start to remove buckets from the last bucket buffer) => https://github.com/zeebe-io/zb-util/commit/6dbbe7cc60b36d78549a84cddd1f4abf82f2d75c

h3. Implementation

* Dead code
** `ZbMap#blockCountPerBucket`
** `io.zeebe.map.ZbMap.setLoadFactorOverflowLimit(double)`
** `io.zeebe.map.BucketBufferArray.getBucketFillCount(int, int)`
* `ZbMapBucketMergeHelper`
** `tryMergingBuckets` and `tryMerging` can be one method
* There are two concepts of removeable, one is `BucketBufferArray#isBucketRemoveable` and the other is the flagging of a bucket that is conceptually removed but not physically. Rename one of them, e.g. the latter to `ABANDONED_BUCKET` to make clear this is not the same.

h3. Tests

* Don't have assertions in `given` and `when` parts. The comments are sufficient to understand the situation and that this is actually the situation should be covered by other tests.
* Variables that are pointers to buckets can be named like the buckets they point to, e.g. `o2Pointer` instead of `bucketOverflowPointer`. This makes it easier to connect the comments with the code
* Some assertions can be stronger: when a test asserts that after removal, certain bucket pointers are > 0, we can also assert the exact pointer value based on the values we fetched in the `given` part
* `BucketBufferArrayTest`
** some longer code blocks in `given` parts => more empty lines help reading
** setting and reading a key-value pair can be extracted into helpers
* There are some unused local variables

**Comment by Zelldon** [comment]
Hey @ThorbenLindhauer ,

I followed your review hints and as discussed created a follow up issue for the documentation of the conceptual layout. https://github.com/zeebe-io/zb-util/issues/38
